### ISSUE TITLE
Can you delete the Dbut-set-Emin-emocrust-20241204 ? 

### ISSUE THREAD

**Issue by dussartc** [circinusX1/ghitara_com#4]
Hello,
I just wanted to test the tool, I didn't realised the uploads were public. Can you please delete the Dbut-set-Emin-emocrust-20241204? 
Thank you

**Comment by marriusco** [comment]
Hi,
Deleted,
Use the converter from: (uses same converter code), public on this github,

http://tools.webhop.net/index.php?art=./tools/software/miditogp.php
